# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-07 23:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2016, 8, 7, 23, 46, 40, 44212, tzinfo=utc))),
                ('owner', models.CharField(default='dummy', max_length=200)),
                ('contents', models.TextField()),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
