# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 11:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplelist',
            name='contentjson',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 8, 11, 20, 23, 591029, tzinfo=utc)),
        ),
    ]
